// src/app/pages/notificaciones/notificaciones.component.ts
import { Component } from '@angular/core';
import { ModulePlaceholderComponent } from '../module-placeholder/module-placeholder.component';

@Component({
  selector: 'app-notificaciones',
  standalone: true,
  imports: [ModulePlaceholderComponent],
  template: `<app-module-placeholder title="Notificaciones" description="Revisa y administra todas las notificaciones del sistema." icon="bell" parentModule="" />`,
})
export class NotificacionesComponent {}

// app/dashboard/notificaciones/page.tsx
import { Bell } from "lucide-react"
import { ModulePlaceholder } from "@/components/module-placeholder"

export default function NotificacionesPage() {
  return (
    <ModulePlaceholder
      title="Notificaciones"
      description="Revisa y administra todas las notificaciones del sistema."
      icon={Bell}
      parentModule=""
    />
  )
}
