// components/ui/card.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "rounded-lg border bg-card text-card-foreground shadow-sm",
        className
      )}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("flex flex-col space-y-1.5 p-6", className)}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"h3">) {
  return (
    <h3
      className={cn(
        "text-2xl font-semibold leading-none tracking-tight",
        className
      )}
      {...props}
    />
  )
}

function CardDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      className={cn("text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return <div className={cn("p-6 pt-0", className)} {...props} />
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("flex items-center p-6 pt-0", className)}
      {...props}
    />
  )
}

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
}

// src/app/shared/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  standalone: true,
  templateUrl: './card.component.html',
  styleUrl: './card.component.scss',
})
export class CardComponent {
  @Input() class = '';
}

@Component({
  selector: 'app-card-header',
  standalone: true,
  template: `<div class="flex flex-col space-y-1.5 p-6" [class]="class"><ng-content /></div>`,
})
export class CardHeaderComponent {
  @Input() class = '';
}

@Component({
  selector: 'app-card-title',
  standalone: true,
  template: `<h3 class="text-lg font-semibold leading-none tracking-tight" [class]="class"><ng-content /></h3>`,
})
export class CardTitleComponent {
  @Input() class = '';
}

@Component({
  selector: 'app-card-description',
  standalone: true,
  template: `<p class="text-sm text-muted-foreground" [class]="class"><ng-content /></p>`,
})
export class CardDescriptionComponent {
  @Input() class = '';
}

@Component({
  selector: 'app-card-content',
  standalone: true,
  template: `<div class="p-6 pt-0" [class]="class"><ng-content /></div>`,
})
export class CardContentComponent {
  @Input() class = '';
}

<div
  class="rounded-lg border border-border bg-card text-card-foreground shadow-sm"
  [class]="class"
>
  <ng-content />
</div>
