// angular-app/src/app/components/ambulance-transfer-form/ambulance-transfer-form.component.ts
import { Component, output, OnInit, OnDestroy } from '@angular/core';
import {
  FormGroup,
  FormControl,
  ReactiveFormsModule,
} from '@angular/forms';
import { Subscription } from 'rxjs';
import { AmbulanceTransfer, TransferType } from '../../models/types';

@Component({
  selector: 'app-ambulance-transfer-form',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="flex flex-col gap-5">
      <!-- Transfer Type & Reason -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div class="flex flex-col gap-1.5">
          <label class="label" for="transferType">Tipo de Traslado *</label>
          <select id="transferType" class="select" [formControl]="form.controls.transferType">
            <option value="">Seleccionar tipo</option>
            <option value="SIMPLE">Simple</option>
            <option value="REDONDO">Redondo</option>
          </select>
        </div>

        <div class="flex flex-col gap-1.5">
          <label class="label" for="dateTime">Fecha y Hora del Traslado *</label>
          <input id="dateTime" type="datetime-local" class="input" [formControl]="form.controls.dateTime" />
        </div>

        <div class="flex flex-col gap-1.5 sm:col-span-2">
          <label class="label" for="reason">Motivo del Traslado *</label>
          <input id="reason" type="text" class="input" placeholder="Motivo del traslado" [formControl]="form.controls.reason" />
        </div>
      </div>

      <!-- Origin -->
      <fieldset class="border rounded-lg p-4">
        <legend class="text-sm font-semibold px-2 text-foreground">Lugar de Origen</legend>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div class="flex flex-col gap-1.5">
            <label class="label" for="originPlace">Lugar *</label>
            <input id="originPlace" type="text" class="input" placeholder="Ej: Hospital Central" [formControl]="form.controls.originPlace" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="originAddress">Direccion *</label>
            <input id="originAddress" type="text" class="input" placeholder="Ej: Cra 10 #20-30" [formControl]="form.controls.originAddress" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="originDept">Departamento *</label>
            <input id="originDept" type="text" class="input" placeholder="Ej: Cundinamarca" [formControl]="form.controls.originDepartment" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="originMun">Municipio *</label>
            <input id="originMun" type="text" class="input" placeholder="Ej: Bogota" [formControl]="form.controls.originMunicipality" />
          </div>
        </div>
      </fieldset>

      <!-- Destination -->
      <fieldset class="border rounded-lg p-4">
        <legend class="text-sm font-semibold px-2 text-foreground">Lugar de Destino</legend>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div class="flex flex-col gap-1.5">
            <label class="label" for="destPlace">Lugar *</label>
            <input id="destPlace" type="text" class="input" placeholder="Ej: Fundacion Cardioinfantil" [formControl]="form.controls.destPlace" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="destAddress">Direccion *</label>
            <input id="destAddress" type="text" class="input" placeholder="Ej: Calle 163A #13B-60" [formControl]="form.controls.destAddress" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="destDept">Departamento *</label>
            <input id="destDept" type="text" class="input" placeholder="Ej: Cundinamarca" [formControl]="form.controls.destDepartment" />
          </div>
          <div class="flex flex-col gap-1.5">
            <label class="label" for="destMun">Municipio *</label>
            <input id="destMun" type="text" class="input" placeholder="Ej: Bogota" [formControl]="form.controls.destMunicipality" />
          </div>
        </div>
      </fieldset>

      <!-- Destination Service -->
      <div class="flex flex-col gap-1.5">
        <label class="label" for="destService">Servicio del Destino *</label>
        <select id="destService" class="select" [formControl]="form.controls.destService">
          <option value="">Seleccionar servicio</option>
          <option value="UCI">UCI</option>
          <option value="PSIQUIATRIA">Psiquiatria</option>
          <option value="URGENCIAS">Urgencias</option>
          <option value="CIRUGIA">Cirugia</option>
          <option value="MEDICINA_INTERNA">Medicina Interna</option>
          <option value="PEDIATRIA">Pediatria</option>
          <option value="GINECOLOGIA">Ginecologia</option>
          <option value="ONCOLOGIA">Oncologia</option>
        </select>
      </div>

      <!-- Vital Support -->
      <fieldset class="border rounded-lg p-4">
        <legend class="text-sm font-semibold px-2 text-foreground">Tipo de Soporte Vital</legend>
        <div class="flex flex-col gap-3">
          <div class="flex items-center gap-2">
            <input id="infusionPump" type="checkbox" class="checkbox" [formControl]="form.controls.infusionPump" />
            <label for="infusionPump" class="font-normal cursor-pointer text-sm">
              Bomba de Infusion
            </label>
          </div>
          <div class="flex items-center gap-2">
            <input id="mechanicalVentilator" type="checkbox" class="checkbox" [formControl]="form.controls.mechanicalVentilator" />
            <label for="mechanicalVentilator" class="font-normal cursor-pointer text-sm">
              Ventilador Mecanico
            </label>
          </div>
        </div>
      </fieldset>

      <!-- Observation -->
      <div class="flex flex-col gap-1.5">
        <label class="label" for="ambObs">Observacion (opcional)</label>
        <textarea
          id="ambObs"
          class="textarea"
          rows="3"
          placeholder="Observaciones adicionales del traslado..."
          [formControl]="form.controls.observation"
        ></textarea>
      </div>

      <!-- EPP -->
      <div class="flex items-center gap-2 p-3 rounded-lg border bg-muted/30">
        <input id="requiresEPP" type="checkbox" class="checkbox" [formControl]="form.controls.requiresEPP" />
        <label for="requiresEPP" class="font-normal cursor-pointer text-sm">
          Requiere Elemento de Proteccion Personal (EPP)
        </label>
      </div>
    </div>
  `,
})
export class AmbulanceTransferFormComponent implements OnInit, OnDestroy {
  onDataChange = output<AmbulanceTransfer | null>();

  form = new FormGroup({
    transferType: new FormControl(''),
    reason: new FormControl(''),
    dateTime: new FormControl(''),
    originPlace: new FormControl(''),
    originAddress: new FormControl(''),
    originDepartment: new FormControl(''),
    originMunicipality: new FormControl(''),
    destPlace: new FormControl(''),
    destAddress: new FormControl(''),
    destDepartment: new FormControl(''),
    destMunicipality: new FormControl(''),
    destService: new FormControl(''),
    infusionPump: new FormControl(false),
    mechanicalVentilator: new FormControl(false),
    observation: new FormControl(''),
    requiresEPP: new FormControl(false),
  });

  private sub!: Subscription;

  ngOnInit(): void {
    this.sub = this.form.valueChanges.subscribe((val) => {
      const isValid =
        val.transferType !== '' &&
        (val.reason ?? '').trim() !== '' &&
        val.dateTime !== '' &&
        (val.originPlace ?? '').trim() !== '' &&
        (val.originAddress ?? '').trim() !== '' &&
        (val.originDepartment ?? '').trim() !== '' &&
        (val.originMunicipality ?? '').trim() !== '' &&
        (val.destPlace ?? '').trim() !== '' &&
        (val.destAddress ?? '').trim() !== '' &&
        (val.destDepartment ?? '').trim() !== '' &&
        (val.destMunicipality ?? '').trim() !== '' &&
        val.destService !== '';

      if (isValid) {
        const data: AmbulanceTransfer = {
          transferType: val.transferType as TransferType,
          reason: val.reason ?? '',
          dateTime: val.dateTime ?? '',
          origin: {
            place: val.originPlace ?? '',
            address: val.originAddress ?? '',
            department: val.originDepartment ?? '',
            municipality: val.originMunicipality ?? '',
          },
          destination: {
            place: val.destPlace ?? '',
            address: val.destAddress ?? '',
            department: val.destDepartment ?? '',
            municipality: val.destMunicipality ?? '',
          },
          destinationService: val.destService ?? '',
          vitalSupport: {
            infusionPump: val.infusionPump ?? false,
            mechanicalVentilator: val.mechanicalVentilator ?? false,
          },
          observation: val.observation ?? '',
          requiresEPP: val.requiresEPP ?? false,
          trips: [
            {
              id: `trip-${Date.now()}`,
              tripNumber: 1,
              status: 'PENDIENTE',
              driver: null,
              origin: val.originPlace ?? '',
              destination: val.destPlace ?? '',
            },
          ],
        };
        this.onDataChange.emit(data);
      } else {
        this.onDataChange.emit(null);
      }
    });
  }

  ngOnDestroy(): void {
    this.sub?.unsubscribe();
  }
}

// components/ambulance-transfer-form.tsx
"use client"

import { useState, useEffect } from "react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import type { AmbulanceTransfer, TransferType } from "@/lib/types"

interface AmbulanceTransferFormProps {
  onDataChange: (data: AmbulanceTransfer | null) => void
}

export function AmbulanceTransferForm({ onDataChange }: AmbulanceTransferFormProps) {
  const [transferType, setTransferType] = useState<TransferType | "">("")
  const [reason, setReason] = useState("")
  const [dateTime, setDateTime] = useState("")
  const [originPlace, setOriginPlace] = useState("")
  const [originAddress, setOriginAddress] = useState("")
  const [originDepartment, setOriginDepartment] = useState("")
  const [originMunicipality, setOriginMunicipality] = useState("")
  const [destPlace, setDestPlace] = useState("")
  const [destAddress, setDestAddress] = useState("")
  const [destDepartment, setDestDepartment] = useState("")
  const [destMunicipality, setDestMunicipality] = useState("")
  const [destService, setDestService] = useState("")
  const [infusionPump, setInfusionPump] = useState(false)
  const [mechanicalVentilator, setMechanicalVentilator] = useState(false)
  const [observation, setObservation] = useState("")
  const [requiresEPP, setRequiresEPP] = useState(false)

  useEffect(() => {
    const isValid =
      transferType !== "" &&
      reason.trim() !== "" &&
      dateTime !== "" &&
      originPlace.trim() !== "" &&
      originAddress.trim() !== "" &&
      originDepartment.trim() !== "" &&
      originMunicipality.trim() !== "" &&
      destPlace.trim() !== "" &&
      destAddress.trim() !== "" &&
      destDepartment.trim() !== "" &&
      destMunicipality.trim() !== "" &&
      destService !== ""

    if (isValid) {
      const data: AmbulanceTransfer = {
        transferType: transferType as TransferType,
        reason,
        dateTime,
        origin: {
          place: originPlace,
          address: originAddress,
          department: originDepartment,
          municipality: originMunicipality,
        },
        destination: {
          place: destPlace,
          address: destAddress,
          department: destDepartment,
          municipality: destMunicipality,
        },
        destinationService: destService,
        vitalSupport: {
          infusionPump,
          mechanicalVentilator,
        },
        observation,
        requiresEPP,
        trips: [
          {
            id: `trip-${Date.now()}`,
            tripNumber: 1,
            status: "PENDIENTE",
            driver: null,
            origin: originPlace,
            destination: destPlace,
          },
        ],
      }
      onDataChange(data)
    } else {
      onDataChange(null)
    }
  }, [
    transferType, reason, dateTime,
    originPlace, originAddress, originDepartment, originMunicipality,
    destPlace, destAddress, destDepartment, destMunicipality,
    destService, infusionPump, mechanicalVentilator, observation, requiresEPP,
    onDataChange,
  ])

  return (
    <div className="flex flex-col gap-5">
      {/* Transfer Type & Reason */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="transferType">Tipo de Traslado *</Label>
          <Select
            value={transferType}
            onValueChange={(val) => setTransferType(val as TransferType)}
          >
            <SelectTrigger id="transferType" className="w-full">
              <SelectValue placeholder="Seleccionar tipo" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="SIMPLE">Simple</SelectItem>
              <SelectItem value="REDONDO">Redondo</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="flex flex-col gap-1.5">
          <Label htmlFor="dateTime">Fecha y Hora del Traslado *</Label>
          <Input
            id="dateTime"
            type="datetime-local"
            value={dateTime}
            onChange={(e) => setDateTime(e.target.value)}
          />
        </div>

        <div className="flex flex-col gap-1.5 sm:col-span-2">
          <Label htmlFor="reason">Motivo del Traslado *</Label>
          <Input
            id="reason"
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder="Motivo del traslado"
          />
        </div>
      </div>

      {/* Origin */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-semibold px-2 text-foreground">Lugar de Origen</legend>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="originPlace">Lugar *</Label>
            <Input
              id="originPlace"
              value={originPlace}
              onChange={(e) => setOriginPlace(e.target.value)}
              placeholder="Ej: Hospital Central"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="originAddress">Direccion *</Label>
            <Input
              id="originAddress"
              value={originAddress}
              onChange={(e) => setOriginAddress(e.target.value)}
              placeholder="Ej: Cra 10 #20-30"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="originDept">Departamento *</Label>
            <Input
              id="originDept"
              value={originDepartment}
              onChange={(e) => setOriginDepartment(e.target.value)}
              placeholder="Ej: Cundinamarca"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="originMun">Municipio *</Label>
            <Input
              id="originMun"
              value={originMunicipality}
              onChange={(e) => setOriginMunicipality(e.target.value)}
              placeholder="Ej: Bogota"
            />
          </div>
        </div>
      </fieldset>

      {/* Destination */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-semibold px-2 text-foreground">Lugar de Destino</legend>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="destPlace">Lugar *</Label>
            <Input
              id="destPlace"
              value={destPlace}
              onChange={(e) => setDestPlace(e.target.value)}
              placeholder="Ej: Fundacion Cardioinfantil"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="destAddress">Direccion *</Label>
            <Input
              id="destAddress"
              value={destAddress}
              onChange={(e) => setDestAddress(e.target.value)}
              placeholder="Ej: Calle 163A #13B-60"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="destDept">Departamento *</Label>
            <Input
              id="destDept"
              value={destDepartment}
              onChange={(e) => setDestDepartment(e.target.value)}
              placeholder="Ej: Cundinamarca"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="destMun">Municipio *</Label>
            <Input
              id="destMun"
              value={destMunicipality}
              onChange={(e) => setDestMunicipality(e.target.value)}
              placeholder="Ej: Bogota"
            />
          </div>
        </div>
      </fieldset>

      {/* Destination Service */}
      <div className="flex flex-col gap-1.5">
        <Label htmlFor="destService">Servicio del Destino *</Label>
        <Select value={destService} onValueChange={setDestService}>
          <SelectTrigger id="destService" className="w-full">
            <SelectValue placeholder="Seleccionar servicio" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="UCI">UCI</SelectItem>
            <SelectItem value="PSIQUIATRIA">Psiquiatria</SelectItem>
            <SelectItem value="URGENCIAS">Urgencias</SelectItem>
            <SelectItem value="CIRUGIA">Cirugia</SelectItem>
            <SelectItem value="MEDICINA_INTERNA">Medicina Interna</SelectItem>
            <SelectItem value="PEDIATRIA">Pediatria</SelectItem>
            <SelectItem value="GINECOLOGIA">Ginecologia</SelectItem>
            <SelectItem value="ONCOLOGIA">Oncologia</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Vital Support */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-semibold px-2 text-foreground">
          Tipo de Soporte Vital
        </legend>
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <Checkbox
              id="infusionPump"
              checked={infusionPump}
              onCheckedChange={(val) => setInfusionPump(val === true)}
            />
            <Label htmlFor="infusionPump" className="font-normal cursor-pointer">
              Bomba de Infusion
            </Label>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox
              id="mechanicalVentilator"
              checked={mechanicalVentilator}
              onCheckedChange={(val) => setMechanicalVentilator(val === true)}
            />
            <Label htmlFor="mechanicalVentilator" className="font-normal cursor-pointer">
              Ventilador Mecanico
            </Label>
          </div>
        </div>
      </fieldset>

      {/* Observation */}
      <div className="flex flex-col gap-1.5">
        <Label htmlFor="ambObs">Observacion (opcional)</Label>
        <Textarea
          id="ambObs"
          value={observation}
          onChange={(e) => setObservation(e.target.value)}
          placeholder="Observaciones adicionales del traslado..."
          rows={3}
        />
      </div>

      {/* EPP */}
      <div className="flex items-center gap-2 p-3 rounded-lg border bg-muted/30">
        <Checkbox
          id="requiresEPP"
          checked={requiresEPP}
          onCheckedChange={(val) => setRequiresEPP(val === true)}
        />
        <Label htmlFor="requiresEPP" className="font-normal cursor-pointer">
          Requiere Elemento de Proteccion Personal (EPP)
        </Label>
      </div>
    </div>
  )
}
