// src/app/pages/module-placeholder/module-placeholder.component.ts
import { Component, Input } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import {
  CardComponent,
  CardContentComponent,
} from '../../shared/card/card.component';

@Component({
  selector: 'app-module-placeholder',
  standalone: true,
  imports: [LucideAngularModule, CardComponent, CardContentComponent],
  templateUrl: './module-placeholder.component.html',
  styleUrl: './module-placeholder.component.scss',
})
export class ModulePlaceholderComponent {
  @Input() title = '';
  @Input() description = '';
  @Input() icon = '';
  @Input() parentModule = '';
}

<div class="flex flex-col gap-6">
  <div>
    @if (parentModule) {
      <span class="text-xs font-medium uppercase tracking-wider text-primary">
        {{ parentModule }}
      </span>
    }
    <h1 class="text-2xl font-bold text-foreground">{{ title }}</h1>
    <p class="mt-1 text-sm text-muted-foreground">{{ description }}</p>
  </div>
  <app-card class="border-border">
    <app-card-content class="flex flex-col items-center justify-center py-16">
      <div
        class="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 text-primary"
      >
        <lucide-icon [name]="icon" [size]="32"></lucide-icon>
      </div>
      <h2 class="mt-4 text-lg font-semibold text-foreground">{{ title }}</h2>
      <p class="mt-2 max-w-sm text-center text-sm text-muted-foreground">
        {{ description }}
      </p>
      <div
        class="mt-6 flex items-center gap-2 rounded-full bg-secondary px-4 py-2 text-xs text-muted-foreground"
      >
        <lucide-icon name="construction" [size]="14"></lucide-icon>
        <span>Modulo en desarrollo</span>
      </div>
    </app-card-content>
  </app-card>
</div>

// components/module-placeholder.tsx
import { Construction } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import type { LucideIcon } from "lucide-react"

interface ModulePlaceholderProps {
  title: string
  description: string
  icon: LucideIcon
  parentModule?: string
}

export function ModulePlaceholder({
  title,
  description,
  icon: Icon,
  parentModule,
}: ModulePlaceholderProps) {
  return (
    <div className="flex flex-col gap-6">
      <div>
        {parentModule && (
          <span className="text-xs font-medium uppercase tracking-wider text-primary">
            {parentModule}
          </span>
        )}
        <h1 className="text-2xl font-bold text-foreground">{title}</h1>
        <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      </div>
      <Card className="border-border">
        <CardContent className="flex flex-col items-center justify-center py-16">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 text-primary">
            <Icon className="h-8 w-8" />
          </div>
          <h2 className="mt-4 text-lg font-semibold text-foreground">
            {title}
          </h2>
          <p className="mt-2 max-w-sm text-center text-sm text-muted-foreground">
            {description}
          </p>
          <div className="mt-6 flex items-center gap-2 rounded-full bg-secondary px-4 py-2 text-xs text-muted-foreground">
            <Construction className="h-3.5 w-3.5" />
            <span>Modulo en desarrollo</span>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
