// src/app/pages/soporte/soporte.component.ts
import { Component } from '@angular/core';
import { ModulePlaceholderComponent } from '../module-placeholder/module-placeholder.component';

@Component({
  selector: 'app-soporte',
  standalone: true,
  imports: [ModulePlaceholderComponent],
  template: `<app-module-placeholder title="Soporte" description="Centro de ayuda, documentacion y contacto con soporte tecnico." icon="help-circle" parentModule="" />`,
})
export class SoporteComponent {}

// app/dashboard/soporte/page.tsx
import { HelpCircle } from "lucide-react"
import { ModulePlaceholder } from "@/components/module-placeholder"

export default function SoportePage() {
  return (
    <ModulePlaceholder
      title="Soporte"
      description="Centro de ayuda, documentacion y contacto con soporte tecnico."
      icon={HelpCircle}
      parentModule=""
    />
  )
}
