// src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { StatsCardsComponent } from './stats-cards/stats-cards.component';
import { ModuleCardsComponent } from './module-cards/module-cards.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [StatsCardsComponent, ModuleCardsComponent],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent {}

<div class="flex flex-col gap-8">
  <!-- Welcome -->
  <div>
    <h1 class="text-2xl font-bold text-foreground" style="text-wrap: balance">
      Bienvenido, Administrador
    </h1>
    <p class="mt-1 text-sm text-muted-foreground">
      Aqui tienes un resumen general de tu sistema.
    </p>
  </div>

  <!-- Stats -->
  <app-stats-cards />

  <!-- Module & Link Cards -->
  <app-module-cards />
</div>

// app/dashboard/page.tsx
import { StatsCards } from "@/components/stats-cards"
import { ModuleCards } from "@/components/module-cards"

export default function DashboardPage() {
  return (
    <div className="flex flex-col gap-8">
      {/* Welcome */}
      <div>
        <h1 className="text-2xl font-bold text-foreground text-balance">
          Bienvenido, Administrador
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Aqui tienes un resumen general de tu sistema.
        </p>
      </div>

      {/* Stats */}
      <StatsCards />

      {/* Module & Link Cards */}
      <ModuleCards />
    </div>
  )
}
